config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  get 'pages/index'

  get 'pages/contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @images = ["http://static6.businessinsider.com/image/55918b77ecad04a3465a0a63/nbc-fires-donald-trump-after-he-calls-mexicans-rapists-and-drug-runners.jpg",
    "https://pbs.twimg.com/profile_images/715620604498436098/LW9o64IM.jpg",
    "http://www.newyorker.com/wp-content/uploads/2016/05/04222016-Cartoon-Lounge-1200-630.jpg",
    "http://www.palmbeachpost.com/rf/image/Pub/p7/CmgSharedContent/2016/02/29/Images/photos.medleyphoto.8848927.jpg",
    "http://www.telegraph.co.uk/content/dam/opinion/2016/03/30/trump1-xlarge_trans_NvBQzQNjv4BqpJliwavx4coWFCaEkEsb3kvxIt-lGGWCWqwLa_RXJU8.jpg",
    "https://thedodolive-img.rbl.ms/simage/https%3A%2F%2Fassets.rbl.ms%2F1569172%2F1216x700.jpg/2000,2000/ZPcHhzop%2F8%2BtxQm5/img.jpg",
    "https://thumbs.dreamstime.com/z/donald-trump-president-cartoon-illustration-showing-head-american-real-estate-magnate-television-personality-politician-63095349.jpg",
    "https://s-media-cache-ak0.pinimg.com/736x/03/1d/0f/031d0f30b36713ba42ea6f04f9114b31.jpg"]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trump Portfolio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="page-wrapper">
      <div class="container-fluid">
        <p class="title">TRUMP</p>
        <ul class="nav">
          <li><%= link_to("Home", root_path) %></li>
          <li><%= link_to("Contact", pages_contact_url) %></li>
        </ul>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<h2>Twiiter: <a href='https://twitter.com/realDonaldTrump' target="_blank">@realDonaldTrump</a></h2>

app/views/pages/index.html.erb
<div class="flex-container">
  <% @images.each do |item| %>
    <div class="flex-item">
      <img src="<%= item %>">
      <p>"You're fired!"</p>
    </div>
  <% end %>
</div>